language: node_js
node_js:
- node
cache: npm
services:
- docker
before_install:
  # install heroku CLI
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
install:
- npm install
env:
  global:
  - DOCKER_IMAGE=agranado2k/js-google-book-api
  - DOCKER_TAG=$TRAVIS_COMMIT
jobs:
  include:
  - stage: Unit Tests
    script: npm run test:unit
  - stage: Build image
    script:
      docker build . -t $DOCKER_IMAGE:$DOCKER_TAG &&
      ./scripts/pushDockerImage.sh $DOCKER_TAG
  - stage: E2E Tests
    script:
      docker pull $DOCKER_IMAGE:$DOCKER_TAG &&
      DOCKER_TAG=$TRAVIS_COMMIT npm run test:e2e:ci
  - stage: Release
    script: echo "Deploying to Heroku ..."
    deploy:
      provider: script
      skip_cleanup: true
      script: DOCKER_TAG=$DOCKER_TAG npx semantic-release
      on:
        branches: master
